#!/usr/bin/env bash
# Commit message guard — blocks AI tool attribution in commit messages.
#
# Rule (AGENTS.md → Git Protocol): commits describe the change, not the
# tooling. No Co-Authored-By lines naming AI tools, no "Generated with"
# footers, no robot emojis. Scans the full history — the rule applies
# repo-wide, and the history is short by design.
#
# Usage: bash scripts/check-commits.sh

set -u

if ! git rev-parse HEAD > /dev/null 2>&1; then
  echo "❌ Not in a git repository"
  exit 1
fi

VIOLATIONS=$(git log --format='%h %s%n%b' \
  | grep -inE 'co-authored-by:.*(claude|codex|copilot|chatgpt|gpt|gemini|cursor|devin|aider|anthropic|openai)|generated with|generated by (claude|codex|copilot|chatgpt|ai)|🤖' \
  || true)

if [ -n "$VIOLATIONS" ]; then
  echo "❌ AI attribution found in commit messages:"
  echo "$VIOLATIONS"
  echo ""
  echo "Rule: no AI tool attribution in commits (AGENTS.md → Git Protocol)."
  echo "Rewrite the offending commit message(s) before merging."
  exit 1
fi

echo "✅ Commit messages clean — no AI attribution"
